name: Manual Workflow Langchain
on:
  workflow_dispatch: {}

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
        env:
          ACTIVELOOP_TOKEN: ${{ secrets.ACTIVELOOP_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          BUCKET: ${{ secrets.AWS_S3_BUCKET }}         
      - name: Run tests script
        working-directory: .github/langchain-tests
        run: |
          bash order_of_runing.sh
